matrix:
  include:
    - language: go
      go:
        - "1.10.x"
      before_script:
        - cd mrc5163/sumation
      script:
        - go build
        - go test -v -cover
  
#deploy:
#  provider: lambda
#  function_name: "Alexa-travisci-skill"
#  region: "us-east-1"
#  role: "arn:aws:iam::664183912372:role/travis-deploy-lambda"
#  runtime: "go1.x"
#  module_name: "hello/hello"
#  handler_name: "HandleRequest"
#  access_key_id: $AWS_ACCESS_KEY_ID
#  secret_access_key: $AWS_SECRET_ACCESS_KEY
