matrix:
  include:
    - language: go
      go:
        - "1.10.x"
      before_install:
        - go get -v github.com/aws/aws-lambda-go/lambda
      script:
        - cd src
        - go build main.go
        - cd ../..
        - zip -r travislambda.zip TravisCI-Lambda
  
deploy:
  provider: lambda
  function_name: "AlexaTravisCISkill"
  region: "us-east-1"
  role: "arn:aws:iam::664183912372:role/travis-deploy-lambda"
  runtime: "go1.x"
  #module_name: "alexa-skill/internal/pkg/travis"
  module_name: "TravisCI-Lambda/src/main"
  handler_name: "AlexaTravisCISkill"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  verbose: true
  zip: TravisCI-Lambda.zip
