matrix:
  include:
    - language: go
      go:
        - "1.10.x"
      script:
        - cd mrc5163/sumation
        - go build
        - go test -v -cover
        - cd ../../pkg/travis
        - go build
        - cd ../../src
        - go build main.go
        - zip travislambda.zip
  
deploy:
  provider: lambda
  function_name: "AlexaTravisCISkill"
  region: "us-east-1"
  role: "arn:aws:iam::664183912372:role/travis-deploy-lambda"
  runtime: "go1.x"
  #module_name: "alexa-skill/internal/pkg/travis"
  module_name: "src/main"
  handler_name: "AlexaTravisCISkill"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  verbose: true
  zip: travislambda.zip
