matrix:
  include:

    - language: node_js
      node_js:
        - "node"
        - "iojs"
      before_script:
        - cd target-app/front-end
      install:
        - npm install -g codecov
      script:
        - npm install
        - npm run build
        - npm run test
        - codecov
